add docs and pypi setup

diff --git a/template_sources/.gitlab-ci.yml.j2 b/template_sources/.gitlab-ci.yml.j2
--- a/template_sources/.gitlab-ci.yml.j2
+++ b/template_sources/.gitlab-ci.yml.j2
@@ -1,13 +1,12 @@
 stages:
   - lint
   - test
-  - image
-  - package
+  - tag
+  - publish
 
 variables:
   GIT_STRATEGY: clone
   IMAGE_NAME: ${NDIP_DOCKER_REPOSITORY}/${CI_PROJECT_PATH}
-  IMAGE_TAG: "0.1.0"
 
 before_script:
   - curl https://code.ornl.gov/rse-deployment/rse-sharables/raw/master/rse-bash-modules.sh -O
@@ -52,13 +51,41 @@ unit-tests:
   tags:
     - rse-multi-builder
 
+docs-test:
+  stage: test
+  script:
+    - docker run -u `id -u`:`id -g` ${IMAGE_NAME}:src-${CI_COMMIT_SHA} bash build_docs.sh
+  tags:
+    - rse-multi-builder
+
+
+tag-release:
+  stage: tag
+  rules:
+    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
+      when: always
+    - when: never
+  script:
+    - git config user.email "$GITLAB_USER_EMAIL"
+    - git config user.name "$GITLAB_USER_NAME"
+    - VERSION=$(cat pyproject.toml | grep "version =" | awk '{ print $3 }' | tr -d '"')
+    - >
+      if [ -z $(git ls-remote --tags origin "$VERSION") ]; then
+        git remote add gitlab https://oauth2:${NDIP_GROUP_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git
+        git tag ${VERSION}
+        git push gitlab ${VERSION} --tags
+      fi
+  tags:
+  - rse-multi-builder
+
 
 build-image:
-  stage: image
+  stage: publish
   variables:
     OVERWRITE_IMAGE: "false"
   when: manual
   script:
+    - IMAGE_TAG=$(cat pyproject.toml | grep "version =" | awk '{ print $3 }' | tr -d '"')
     - docker pull ${IMAGE_NAME}:src-${CI_COMMIT_SHA}
     - docker build -f dockerfiles/Dockerfile -t image .
     - docker tag image ${IMAGE_NAME}:bin-${CI_COMMIT_SHA}
@@ -76,9 +103,8 @@ build-image:
   tags:
     - rse-multi-builder
 
-
 package-build:
-  stage: package
+  stage: publish
   script:
     - >
       docker run
@@ -87,7 +113,29 @@ package-build:
       bash -c "
       poetry config repositories.gitlab_repo ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi &&
       poetry publish -u gitlab-ci-token -p ${CI_JOB_TOKEN} -r gitlab_repo
+      {%- if publish_to_pypi %}
+      poetry publish -u __token__ -p ${PYPI_API_TOKEN}
+      {%- endif %}
       "
   when: manual
   tags:
     - rse-multi-builder
+
+{%- if publish_docs %}
+docs-publish:
+  stage: publish
+  rules:
+    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
+      when: always
+    - when: manual
+  script:
+    - |
+      if [ -z "$READTHEDOCS_WEBHOOK_SECRET" ] || [ -z "$READTHEDOCS_WEBHOOK_URL" ]; then
+        echo "Error: READTHEDOCS_WEBHOOK_SECRET and/or READTHEDOCS_WEBHOOK_URL is not set."
+        exit 1
+      fi
+    - curl -X POST -d "branches=latest" -d "token=${READTHEDOCS_WEBHOOK_SECRET}" -d "default_branch=${CI_COMMIT_BRANCH}" ${READTHEDOCS_WEBHOOK_URL}
+  tags:
+    - rse-multi-builder
+{%- endif %}
+
